= Lisk Documentation
:hide-uri-scheme:
:idprefix:
:toc: preamble
:url_docusaurus: https://docusaurus.io/

This repo houses the Lisk Docs located at https://documentation.lisk.com. All documentation related updates and new content will be tracked and maintained in this repo.

The Lisk documentation uses {url_docusaurus}[Docusaurus^] as a documentation site generator.

== Managing Docs
=== Local Development

```
$ yarn start
```

This command starts a local development server and opens up a browser window. Most changes are reflected live without having to restart the server.

=== Build

```
$ yarn build
```

This command generates static content into the `build` directory and can be served using any static contents hosting service.

=== Deployment

The following command will automatically [build](#build) the docs, and push them to the `gh-pages` branch.
Changes to this branch are automatically deployed under https://liskhq.github.io/lisk-documentation/

Using SSH:

```
$ USE_SSH=true yarn deploy
```

Not using SSH:

```
$ GIT_USER=<Your GitHub username> yarn deploy
```

== Contributors

https://github.com/LiskHQ/lisk-documentation/graphs/contributors

== License

Copyright 2016-2023 Lisk Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
