/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //documentationSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  documentationSidebar: [
   /*  {
      type: 'doc',
      id: 'overview', // document ID
      label: 'Getting started', // sidebar label
    }, */
    {
      type: 'category',
      label: 'About Lisk',
      collapsible: false,
      collapsed: false,
      items: [
        'lisk-chain/about-lisk/network-info',
        'lisk-chain/about-lisk/intro',
        'lisk-chain/about-lisk/fees',
        'lisk-chain/about-lisk/contracts'
      ],
      link: {
        type: 'generated-index',
        description: 'General information about the Lisk chain',
        keywords: ['Lisk','About Lisk', 'Lisk info', 'fees', 'network info'],
      },
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        'lisk-chain/get-started/overview',
        'lisk-chain/get-started/connecting-to-a-wallet',
        'lisk-chain/get-started/import-lsk',
      ],
      link: {
        type: 'generated-index',
        keywords: ['getting started','start', 'overview'],
      },
    },
    {
      type: 'category',
      label: 'Lisk Tools',
      collapsible: true,
      collapsed: false,
      items: [
        'lisk-chain/lisk-tools/deployed-tokens',
        'lisk-chain/lisk-tools/exchanges',
        'lisk-chain/lisk-tools/wallets',
        'lisk-chain/lisk-tools/bridges',
        'lisk-chain/lisk-tools/node-providers',
        'lisk-chain/lisk-tools/faucets',
        'lisk-chain/lisk-tools/interoperability',
        'lisk-chain/lisk-tools/oracles',
        'lisk-chain/lisk-tools/utilities',
        'lisk-chain/lisk-tools/indexers'
      ],
      link: {
        type: 'generated-index',
        keywords: ['tools','resources'],
      },
    }
  ],

  pannaSidebar: [
    'panna/panna-intro'
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Developer Guides',
      collapsible: false,
      collapsed: false,
      items: [
        'guides/web3-app-development',
        {
          type: 'category',
          label: 'Deploying a Smart Contract',
          collapsible: true,
          collapsed: true,
          items: [
            'guides/deploying-smart-contract/with-Foundry',
            'guides/deploying-smart-contract/with-Hardhat',
            'guides/deploying-smart-contract/with-Remix',
            'guides/deploying-smart-contract/with-thirdweb',
          ],
          link: {
            type: 'generated-index',
            keywords: ['guides', 'smart contracts', 'deployment'],
          },
        },
        {
          type: 'category',
          label: 'Interacting with the blockchain',
          collapsible: true,
          collapsed: true,
          items: [
            'guides/interacting-with-the-blockchain/viem',
            'guides/interacting-with-the-blockchain/ethers',
            'guides/interacting-with-the-blockchain/web3',
          ],
          link: {
            type: 'generated-index',
            keywords: ['guides', 'interacting', 'api'],
          },
        },
        {
          type: 'category',
          label: 'Bridging an L1 token to Lisk',
          collapsible: true,
          collapsed: true,
          items: [
            'guides/add-token-to-lisk/index',
            'guides/add-token-to-lisk/standard-token',
            'guides/add-token-to-lisk/custom-token',
          ],
          link: {
            type: 'generated-index',
            keywords: ['guides', 'smart contracts', 'bridging', 'superchain token list'],
          },
        },
        {
          type: 'category',
          label: 'Token development',
          collapsible: true,
          collapsed: true,
          items: [
            'guides/token-development/overview',
            'guides/token-development/deploy-erc-20',
            'guides/token-development/deploy-erc-721',
            'guides/token-development/deploy-erc-1155',
          ],
          link: {
            type: 'generated-index',
            keywords: ['guides', 'smart contracts', 'token development', 'token standards', 'erc-20', 'erc-721', 'erc-1155'],
          },
        },
        {
          type: 'category',
          label: 'Using oracle data',
          collapsible: true,
          collapsed: true,
          items: [
            'guides/using-oracle-data/tellor',
            'guides/using-oracle-data/redstone-pull',
            'guides/using-oracle-data/redstone-push',
          ],
          link: {
            type: 'generated-index',
            keywords: ['guides', 'oraclss', 'redstone', 'tellor'],
          },
        },
        'guides/run-a-lisk-node'
      ],
      link: {
        type: 'generated-index',
        slug: '/category/guides',
        description: 'Guides for builders developing apps on Lisk',
        keywords: ['guides','tutorials'],
      },
    }
  ],

  legacySidebar: [
    {
      type: 'category',
      label: 'Lisk L1 legacy chain',
      collapsible: false,
      collapsed: false,
      items: [
        'lisk-l1/legacy-chain-service',
        'lisk-l1/migration-guide',
        'lisk-l1/claiming',

      ],
      link: {
        type: 'generated-index',
        slug: '/category/lisk-l1',
        keywords: ['lisk l1','lisk legacy'],
      },
    },
  ],

  /* userSidebar: [
    {
      type: 'category',
      label: 'Using Lisk',
      collapsible: true,
      collapsed: false,
      items: [
        // 'docs-user/intro-user',
        'docs-user/connecting-to-a-wallet',
        'docs-user/using-lisk/import-lsk',
        'docs-user/claiming',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        'docs-user/governance/overview',
        'docs-user/governance/delegation',
        'docs-user/governance/proposal-lifecycle',
        'docs-user/governance/voting',
      ],
    },
    {
      type: 'category',
      label: 'Staking',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        'docs-user/staking/staking',
        'docs-user/staking/stake-unstake',
        'docs-user/staking/pause-position',
        'docs-user/staking/increase-stake',
        'docs-user/staking/extend-duration',
        'docs-user/staking/early-unlock',
      ],
    },
  ], */
};

export default sidebars;
